services:
  nginx:
    build: nginx
    ports:
      - "8443:443"
    depends_on:
      - web
    networks:
      - backend_network

  db:
    image: postgres:17.2
    restart: always
    volumes:
      - /goinfre/database/data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend_network

  web:
    build: backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CLIENT_ID_42=${CLIENT_ID_42}
      - SECRET_42=${SECRET_42}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - backend_network

  redis:
    image: redis:7
    networks:
      - backend_network
    volumes:
      - /goinfre/database/redis:/data

networks:
  backend_network:
    driver: bridge