# Generated by Django 5.1.6 on 2025-02-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0003_tournamentplayer_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nome do torneio"
            ),
        ),
    ]
