# Generated by Django 5.1.6 on 2025-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_match_round_number_tournamentbye_tournament_byes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='byes',
            field=models.ManyToManyField(blank=True, related_name='tournament_byes', to='matchmaking.tournamentbye'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='tournament_matches', to='matchmaking.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em'),
        ),
    ]
