# Generated by Django 5.1.6 on 2025-03-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_tournament_current_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('pong', 'Pong'), ('tictactoe', 'Tictactoe')], default='pong', max_length=255, verbose_name='Tipo de partida'),
        ),
    ]
