# Generated by Django 5.1.6 on 2025-02-23 14:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0002_alter_match_finished_date_played"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentPlayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=255, verbose_name="Nome de exibição"),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now=True, verbose_name="Entrou em"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nome"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "started_at",
                    models.DateTimeField(null=True, verbose_name="Iniciado em"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(null=True, verbose_name="Finalizado em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matches",
                    models.ManyToManyField(related_name="tournament_matches", to="matchmaking.match"),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="tournament_players",
                        to="matchmaking.tournamentplayer",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_winner",
                        to="matchmaking.tournamentplayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Torneio",
                "verbose_name_plural": "Torneios",
            },
        ),
    ]
