# Generated by Django 5.1.6 on 2025-03-02 02:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_alter_tournament_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número da rodada'),
        ),
        migrations.CreateModel(
            name='TournamentBye',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveIntegerField(verbose_name='Número da rodada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.tournamentplayer')),
            ],
            options={
                'verbose_name': 'Bye do Torneio',
                'verbose_name_plural': 'Byes do Torneio',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='byes',
            field=models.ManyToManyField(related_name='tournament_byes', to='matchmaking.tournamentbye'),
        ),
    ]
